version: '3'

services:
  shopware:
    container_name: "shopware"
    image: dockware/dev:6.4.20.0
    ports:
      - "80:80"
      - "3306:3306"
      - "9998:9998"
      - "9999:9999"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - "XDEBUG_ENABLED=1"

volumes:
  mysql_data:
    name: "shopware_volume"